################ English language ##################
[en]
title = "Evangelical Bulgarian Church"
languageName = "ğŸ‡¬ğŸ‡§"
languageCode = "en-gb"
contentDir = "content/en"
weight = 2
donate = "Give"
link = "/en/give"

################ Bulgarian language ##################
[bg]
title = "Ğ•Ğ²Ğ°Ğ½Ğ³ĞµĞ»ÑĞºĞ° Ğ±ÑŠĞ»Ğ³Ğ°Ñ€ÑĞºĞ° Ñ†ÑŠÑ€ĞºĞ²Ğ°"
languageName = "ğŸ‡§ğŸ‡¬"
languageCode = "bg"
contentDir = "content/bg"
weight = 1
donate = "Ğ”Ğ°Ñ€Ğ¸"
link = "/give"
